spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    initialize: false
    driver-class-name: com.mysql.jdbc.Driver
    database: lego
    host: localhost
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/user
    client:
      client-id: company-service
      client-secret: password
      access-token-uri: http://localhost:8080/oauth/token
      grant-type: client_credentials
      scope: backend
flyway:
  validate-on-migrate: false
server:
  port: 8090
logging.level.org.springframework.web: DEBUG
